
[package]
name = "learn-rust"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["examples/*"]

[dependencies]


[[example]]
name = "hello_world"
path = "examples/hello_world/src/main.rs"
